CRSU-Apps/MetaInsight

fn_analysis.R, server.R, ui.R
General text/minor changes found from user feedback.
=> Text changes

plot.R
The code for the Radial SUCRA plot had to be amended to be compliant with newer versions of {ggplot2}
=> Radial SUCRA code compliant with {ggplot2}

R/DataInputPanel.R, R/DataUpgrade.R, R/DataUpgradePanel.R, tests/testthat/test-DataUpgrade.R, ui.R
This can be extended if we do any more data changes before the next release.
=> Added data upgrade panel

CITATION.cff, README.md, ui.R
=> Updated version number

R/DataWrangling.R, R/fn_analysis.R, server.R, tests/testthat/Binary_long_cov.csv, tests/testthat/Binary_wide_cov.csv, tests/testthat/Cont_long_cov.csv, tests/testthat/Cont_wide_cov.csv, tests/testthat/test-DataWrangling.R, ui.R
I've not updated the text in the data upload tab(s) because the data upload could still change. I have raised Jira issue MR-10 to updated the instructions at the end of the project, when the upload is finalised.
=> MR-3 Added support to data upload for covariate columns in the data

R/DataInputPanel.R, R/DataWrangling.R, R/meta_regression_tab.R, server.R, tests/testthat/test-DataWrangling.R, tests/testthat/test-meta_regression_tab.R, ui.R
Created shell of a tab which is hidden if there are no covariates available. Also fixed issue with data filtering when there are no covariates.
=> Mr 4 placeholder tab

R/covariate_analysis_panel.R, R/meta_regression_data.R, R/meta_regression_tab.R, server.R, tests/testthat/test-covariate_analysis_panel.R, tests/testthat/test-meta_regression_data.R, ui.R
Also ensured that continuous covariates can't be set as binary.
=> MR-15 show regression tab

Binary_wide_cov.csv, R/DataWrangling.R, R/gemtc_analysis.R, tests/testthat/test-DataWrangling.R, tests/testthat/test-gemtc_analysis.R
To do internal testing of new command, you can do the following
`test_data <- read.csv("Binary_wide_cov.csv")`
`prepped_data <- PrepDataGemtc(test_data, "Binary", "covar.DiseaseDuration", "DiseaseDuration")`
`reg_result <- RunCovariateRegression(prepped_data, 'random', 'shared', '1')`
`summary(reg_result)`
You may have to load the functions to your workspace manually (as well as those in `DataWrangling.R`)
=> Mr 1 covariate model

R/DataWrangling.R, R/LoadDataPage.R, tests/testthat/test-DataWrangling.R, tests/testthat/test-LoadDataPage.R
Cleaned treatment names to work with bayesian and meta-regression
=> MR-18 clean treatment labels

R/DataWrangling.R, R/gemtc_analysis.R, tests/testthat/test-DataWrangling.R, tests/testthat/test-gemtc_analysis.R
Added option to choose outcome measure, improved tests, and added LongToWide() (with tests).
Pull requests doesn't have an associated Jira task as this was meant to be part of MR-1 but got forgotten...
=> Mr 1b r roption

R/fn_analysis.R
Issue #106 - title changed to "with studies excluded"
=> Changed title in tab 1b

R/covariate_analysis_panel.R, R/informed_conditional_panel.R, R/meta_regression/covariate_value_panel.R, R/meta_regression_data.R, tests/testthat/test-DataInputPanel.R, tests/testthat/test-covariate_analysis_panel.R, tests/testthat/test-covariate_value_panel.R, tests/testthat/test-meta_regression_data.R
Added inputs to control covariate value in analysis.
=> Mr 20 covariate value input

R/DataInputPanel.R, R/bayesian_analysis_panel.R
Changed event reactives to run off the models, not the buttons (which are unavailable).
=> Fixed ranking panel plots

R/meta_regression_plots.R
Created main plot. This has placeholder functions for the contents of the plot. These will be hooked up when the analysis becomes available.
I've added Clareece as a reviewer because she was on the Jira task.
=> MR-23 main regression plot

R/meta_regression/composite_regression_plot.R, R/meta_regression/indirect_contribution_plot.R, R/meta_regression/plot_colours.R, R/meta_regression_plots.R
Created indirect contribution plot and composite regression plot.
After the changes have been reviewed, but before the branch is merged, I'll move some files around to fix the file structure. No code changes will be made at that stage.
=> Mr 27 contribution plot

R/covariate_analysis_panel.R, R/data_analysis_page.R, R/meta_regression/covariate_value_panel.R, R/meta_regression/regression_plot_panel.R, R/meta_regression_tab.R, tests/testthat/test-covariate_analysis_panel.R
=> MR-24 Regression plot page

R/google_analytics_header.R, server.R
Added app name to cookie module
=> MI-39 Added app name to analytics cookie module

R/DataWrangling.R, tests/testthat/test-DataWrangling.R
Added letter case fixing in to data wrangling. After this is merged, I will merge into `feature-meta-regression` and add tests for covariate column.
=> MI-40 Data column case insensitivity

tests/testthat/test-DataWrangling.R, tests/testthat/test-covariate_analysis_panel.R
Added covariate handling to test cases.
=> MI-40 case insensitive covariate

R/bayes_analysis.R, R/network_structure.R, R/plot.R, R/util.R
Fixed minor bug with naming. Also did minor code tidy-up.
=> MI-43 ranking naming

R/DataInputPanel.R, R/LoadDataPage.R, R/data_analysis_page.R, R/home_page.R, server.R, tests/testthat/test-DataInputPanel.R, tests/testthat/test-LoadDataPage.R
Moved outcome selection and removed banners.
=> MI-44 move outcome selection

R/covariate_analysis_panel.R, R/meta_regression/cov_nodesplit_page.R
Added nodesplit placeholder page.
=> MR-40 Placeholder Nodesplit Tab

R/bayesian/nodesplit/nodesplit_page.R, R/bayesian/nodesplit/nodesplit_panel.R
=> MR-46 Fix nodesplit button text

R/baseline_risk_analysis_panel.R, R/meta_regression/cov_nodesplit_page.R
If I had realised it was this easy I would have done it in the previous task!
=> Mr 48 automatic numbering baseline risk

CITATION.cff, R/DataInputPanel.R, R/home_page.R, README.md, server.R, ui.R
Also added new home page image and text to say we can now upload .xlsx.
To check the troubleshooting link is working properly, you'll probably need to run the app within a browser.
=> Troubleshooting patch

R/DataWrangling.R
Added handling to solve user issue.
=> MI-55 filter empty strings

R/covariate_analysis_panel.R, R/meta_regression/regression_plot_panel.R
Added download button to regression plot
=> MR-54 Regression Download Button

R/contribution_matrix.R, R/meta_regression/regression_plot_panel.R, tests/testthat/helper-contribution_matrix.R, tests/testthat/test-contribution_matrix.R
The details are attached to the Jira task.
=> mr-59-arm-level contribution matrix.

R/LongFormatUploadPanel.R, R/WideFormatUploadPanel.R
Updated data upload instructions to include covariate values
=> MR-10 Data Upload Instructions

R/covariate_analysis_panel.R, R/meta_regression/regression_plot_panel.R
Also added spinner when model is running
=> MR-30 move novel plot

R/DataWrangling.R
The issue occurs whenever the reference treatment is changed manually on the load data tab.
=> mr-65-na-covariate-values

R/create_covariate_summary_plot.R, global.R
Changes to summary plot to match updates to main version of BUGSnet package
=> Mr 66 covariate summary plot update

R/data/data_input_panel.R, R/data/data_validation.R, tests/testthat/data/invalid_data/binary-single-arm-long.csv, tests/testthat/data/invalid_data/binary-single-arm-wide.csv, tests/testthat/data/invalid_data/continuous-single-arm-long.csv, tests/testthat/data/invalid_data/continuous-single-arm-wide.csv, tests/testthat/test-data_validation.R
Also removed duplicated code in the invalid data notification.
=> MI-60 Validate single arm studies

R/data/data_input_panel.R, R/data/data_validation.R, tests/testthat/data/invalid_data/binary-single-arm-long.csv, tests/testthat/data/invalid_data/binary-single-arm-wide.csv, tests/testthat/data/invalid_data/continuous-single-arm-long.csv, tests/testthat/data/invalid_data/continuous-single-arm-wide.csv, tests/testthat/test-data_validation.R
Reverts CRSU-Apps/MetaInsight#193
It was merged into `main` rather than `dev` by accident
=> Revert "MI-60 Validate single arm studies"

R/data/data_input_panel.R, R/data/data_validation.R, tests/testthat/data/invalid_data/binary-single-arm-long.csv, tests/testthat/data/invalid_data/binary-single-arm-wide.csv, tests/testthat/data/invalid_data/continuous-single-arm-long.csv, tests/testthat/data/invalid_data/continuous-single-arm-wide.csv, tests/testthat/test-data_validation.R
Repeat of #193, but into `dev` instead of `main`
=> MI-60 Validate single arm studies (2)

R/study_exclusions_panel.R
Added data_reset reactive val to trigger recalculation of sensitivity data when data is reset
=> MI-69 Fixed data upload issue

R/data/data_wrangling.R, tests/testthat/test-data_wrangling.R
I have added one test for CleanStudies().
There are no tests for CleanStrings(), but this is indirectly tested in the existing tests for CleanTreatmentIds(), which I have left unchanged.
=> Mi 56 wrangle study names

R/home_page.R
I've made the funding statement update in the wiki
https://github.com/CRSU-Apps/.github/wiki/Detailed-Funding-Statement
I also added bnma to the list of packages and corrected a couple of links.
=> MI-84-update-funding-statement

.github/workflows/deploy.yml, renv.lock
Added `sudo apt-get update` before installing package dependencies, otherwise the build was failing
=> Dev workflow 2

renv.lock, renv/activate.R
Ran renv::snapshot() and pushed the new renv.lock and activate.R.
=> Renv for v6.4.0

R/meta_regression/gemtc_analysis.R
Changed `RoundVariance()` to `RoundForDisplay()`
Formatting
=> Hotfix v6.4.1
